In [1]:
import pandas as pd

In [3]:
df = pd.DataFrame({'col1': [1,2,3,4,5],
             'col2': [45,56,67,34,34],
             'col3': "sudh kumar krish ineuron one".split()})

In [4]:
df

col1  col2     col3
0     1    45     sudh
1     2    56    kumar
2     3    67    krish
3     4    34  ineuron
4     5    34      one

In [5]:
df['col4']=df['col1']**2

In [6]:
df

col1  col2     col3  col4
0     1    45     sudh     1
1     2    56    kumar     4
2     3    67    krish     9
3     4    34  ineuron    16
4     5    34      one    25

In [7]:
def test(a):
    return a**2

In [8]:
df['col_4'] = df['col1'].apply(test)

In [10]:
df

col1  col2     col3  col4  col_4
0     1    45     sudh     1      1
1     2    56    kumar     4      4
2     3    67    krish     9      9
3     4    34  ineuron    16     16
4     5    34      one    25     25

In [24]:
def map_str(s):
    if s=='s':
        return 's'
    else:
        return 'z'

def map_str2(s):
    if s[0]=='s':
        return 's'
    else:
        return 'z'

In [17]:
df['col5']=df['col3'].str[0]

In [19]:
df['col6']=df['col5'].apply(map_str)

In [20]:
df

col1  col2     col3  col4  col_4 col5 col6
0     1    45     sudh     1      1    s    s
1     2    56    kumar     4      4    k    z
2     3    67    krish     9      9    k    z
3     4    34  ineuron    16     16    i    z
4     5    34      one    25     25    o    z

In [25]:
df['col7']=df['col3'].apply(map_str2)

In [26]:
df

col1  col2     col3  col4  col_4 col5 col6 col7
0     1    45     sudh     1      1    s    s    s
1     2    56    kumar     4      4    k    z    z
2     3    67    krish     9      9    k    z    z
3     4    34  ineuron    16     16    i    z    z
4     5    34      one    25     25    o    z    z

In [29]:
df['col8']=df['col5'].apply(lambda a:'s' if a=='s' else 'z')

In [30]:
df

col1  col2     col3  col4  col_4 col5 col6 col7 col8
0     1    45     sudh     1      1    s    s    s    s
1     2    56    kumar     4      4    k    z    z    z
2     3    67    krish     9      9    k    z    z    z
3     4    34  ineuron    16     16    i    z    z    z
4     5    34      one    25     25    o    z    z    z

In [31]:
df['col9']=df['col3'].apply(len)

In [32]:
df

col1  col2     col3  col4  col_4 col5 col6 col7 col8  col9
0     1    45     sudh     1      1    s    s    s    s     4
1     2    56    kumar     4      4    k    z    z    z     5
2     3    67    krish     9      9    k    z    z    z     5
3     4    34  ineuron    16     16    i    z    z    z     7
4     5    34      one    25     25    o    z    z    z     3

In [36]:
import math
df['col10']=df['col2'].apply(math.log)

In [37]:
df

col1  col2     col3  col4  col_4 col5 col6 col7 col8  col9     col10
0     1    45     sudh     1      1    s    s    s    s     4  3.806662
1     2    56    kumar     4      4    k    z    z    z     5  4.025352
2     3    67    krish     9      9    k    z    z    z     5  4.204693
3     4    34  ineuron    16     16    i    z    z    z     7  3.526361
4     5    34      one    25     25    o    z    z    z     3  3.526361

In [38]:
import numpy as np

In [39]:
a = np.array([1,2,3,4,5])

In [40]:
a

array([1, 2, 3, 4, 5])

In [41]:
b = np.array(np.mat(a))

In [42]:
b

array([[1, 2, 3, 4, 5]])

In [43]:
np.asanyarray(np.mat(a))

matrix([[1, 2, 3, 4, 5]])

In [44]:
np.asarray(np.mat(a))

array([[1, 2, 3, 4, 5]])

In [71]:
a = np.fromfunction(lambda i,j,z: i*j*z, (4,3,2),dtype=int)

In [72]:
a

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 1],
        [0, 2]],

       [[0, 0],
        [0, 2],
        [0, 4]],

       [[0, 0],
        [0, 3],
        [0, 6]]])

In [73]:
a.reshape(8,3)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [1, 0, 2],
       [0, 0, 0],
       [2, 0, 4],
       [0, 0, 0],
       [3, 0, 6]])

In [47]:
a.shape

(4, 3, 2, 2)

In [48]:
type(a.shape)

tuple

In [49]:
a.dtype

dtype('int32')

In [50]:
b=np.fromfunction(lambda i,j: i*j, (4,3),dtype=int)

In [51]:
pd.DataFrame(b)

0  1  2
0  0  0  0
1  0  1  2
2  0  2  4
3  0  3  6

In [58]:
np.random.rand(3,7)

array([[0.48071583, 0.74983234, 0.96243353, 0.69759519, 0.30755954,
        0.45306558, 0.63581466],
       [0.46783457, 0.35601489, 0.15020697, 0.43593338, 0.29691685,
        0.203273  , 0.25736391],
       [0.42371296, 0.74731922, 0.26841199, 0.13552535, 0.81979102,
        0.20035963, 0.09242541]])

In [69]:
np.random.randint(1,3)

2

In [74]:
arr = np.random.rand(8,5)

In [75]:
arr

array([[0.65384819, 0.30959043, 0.21624533, 0.52773543, 0.76801348],
       [0.19891739, 0.77207199, 0.66463767, 0.38959108, 0.71606264],
       [0.64186791, 0.7630629 , 0.68541991, 0.85436852, 0.76176915],
       [0.32125832, 0.3670553 , 0.08841696, 0.04892233, 0.64533678],
       [0.13230643, 0.94411089, 0.34421443, 0.0121467 , 0.61592705],
       [0.92391204, 0.04738067, 0.63227323, 0.33460148, 0.31107129],
       [0.8758018 , 0.11162417, 0.30816446, 0.99327767, 0.43099665],
       [0.21553583, 0.68543867, 0.52850718, 0.97399142, 0.79136297]])

In [77]:
arr[1:8,0:3]

array([[0.19891739, 0.77207199, 0.66463767],
       [0.64186791, 0.7630629 , 0.68541991],
       [0.32125832, 0.3670553 , 0.08841696],
       [0.13230643, 0.94411089, 0.34421443],
       [0.92391204, 0.04738067, 0.63227323],
       [0.8758018 , 0.11162417, 0.30816446],
       [0.21553583, 0.68543867, 0.52850718]])

In [89]:
arr[[1,3]]

array([[0.19891739, 0.77207199, 0.66463767, 0.38959108, 0.71606264],
       [0.32125832, 0.3670553 , 0.08841696, 0.04892233, 0.64533678]])

In [91]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [96]:
m1 = np.array([[1,2],[3,4]])

In [97]:
m1

array([[1, 2],
       [3, 4]])

In [98]:
m2 = np.array([[2,3],[4,5]])

In [99]:
m2

array([[2, 3],
       [4, 5]])

In [100]:
m1@m2

array([[10, 13],
       [22, 29]])

In [102]:
arr[np.ix_([0,3,5],[1,2])]

array([[0.30959043, 0.21624533],
       [0.3670553 , 0.08841696],
       [0.04738067, 0.63227323]])