In [1]:
import numpy as np

In [2]:
l=[1,77,44,22,90]

In [3]:
np.asarray(l)

array([ 1, 77, 44, 22, 90])

In [5]:
np.ones((3,4,5))

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [6]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [7]:
6+np.identity(5)

array([[7., 6., 6., 6., 6.],
       [6., 7., 6., 6., 6.],
       [6., 6., 7., 6., 6.],
       [6., 6., 6., 7., 6.],
       [6., 6., 6., 6., 7.]])

In [8]:
np.empty((3,4))

array([[1.01106357e-311, 2.47032823e-322, 0.00000000e+000,
        0.00000000e+000],
       [1.08221785e-312, 2.46567317e+179, 5.49321458e-090,
        7.92560439e+165],
       [8.40757015e+164, 1.25909710e-075, 3.99910963e+252,
        2.05471090e+160]])

In [10]:
np.linspace(2,6,10)

array([2.        , 2.44444444, 2.88888889, 3.33333333, 3.77777778,
       4.22222222, 4.66666667, 5.11111111, 5.55555556, 6.        ])

In [12]:
np.arange(1,5,0.2)

array([1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4, 2.6, 2.8, 3. , 3.2, 3.4,
       3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8])

In [19]:
a = np.arange(4,40).reshape((9,4))

In [21]:
a

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35],
       [36, 37, 38, 39]])

In [22]:
a.max(axis=0)

array([36, 37, 38, 39])

In [54]:
b = np.arange(9).reshape(9,1)

In [56]:
c = np.arange(4)

In [50]:
b.shape

(9, 1)

In [57]:
c.shape

(4,)

In [40]:
b.max()

8

In [26]:
a**2

array([[  16,   25,   36,   49],
       [  64,   81,  100,  121],
       [ 144,  169,  196,  225],
       [ 256,  289,  324,  361],
       [ 400,  441,  484,  529],
       [ 576,  625,  676,  729],
       [ 784,  841,  900,  961],
       [1024, 1089, 1156, 1225],
       [1296, 1369, 1444, 1521]], dtype=int32)

In [55]:
a+b

array([[ 4,  5,  6,  7],
       [ 9, 10, 11, 12],
       [14, 15, 16, 17],
       [19, 20, 21, 22],
       [24, 25, 26, 27],
       [29, 30, 31, 32],
       [34, 35, 36, 37],
       [39, 40, 41, 42],
       [44, 45, 46, 47]])

In [58]:
a+c

array([[ 4,  6,  8, 10],
       [ 8, 10, 12, 14],
       [12, 14, 16, 18],
       [16, 18, 20, 22],
       [20, 22, 24, 26],
       [24, 26, 28, 30],
       [28, 30, 32, 34],
       [32, 34, 36, 38],
       [36, 38, 40, 42]])

In [86]:
x = np.array([[[1,2,3],[4,5,6]]])

In [87]:
y=x

In [88]:
y

array([[[1, 2, 3],
        [4, 5, 6]]])

In [89]:
z = np.copy(x)

In [90]:
z

array([[[1, 2, 3],
        [4, 5, 6]]])

In [91]:
x[0][0][0]=100

In [92]:
y

array([[[100,   2,   3],
        [  4,   5,   6]]])

In [93]:
z

array([[[1, 2, 3],
        [4, 5, 6]]])

In [108]:
g = np.array([1,67,88,99])
h =g

In [109]:
id(g)

2046451495728

In [110]:
id(h)

2046451495728

In [113]:
id(g[3])

2046452716944

In [117]:
id(h[3])

2046452717872